# Generated by Django 5.0 on 2023-12-27 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.UUID('282b05ff-c299-4f52-8596-d7954b6b57c3'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.UUIDField(default=uuid.UUID('a4e7119c-3035-46ef-978f-f41d519172f5'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('descritpion', models.CharField(max_length=1000)),
                ('publication_date', models.DateTimeField()),
                ('image_url', models.URLField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.channel')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
