# Generated by Django 5.0.2 on 2024-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
