# Generated by Django 5.0 on 2024-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Mail')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name="Nom d'utilisateur")),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Téléphone')),
                ('adress', models.CharField(max_length=120, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=False, verbose_name='Compte actif ? ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff ? ')),
                ('is_first_login', models.BooleanField(default=True, verbose_name='Premier Login?')),
                ('temporary_password', models.CharField(default=';=bcQek9(|a<', max_length=64, verbose_name='Mot de passe temporaire')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
    ]
