# Generated by Django 5.0 on 2023-12-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomised',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email Confirmé ? '),
        ),
        migrations.AlterField(
            model_name='usercustomised',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Compte actif ? '),
        ),
    ]
