# Generated by Django 5.0 on 2024-02-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomised',
            name='is_first_login',
            field=models.BooleanField(default=True, verbose_name='Premier Login?'),
        ),
        migrations.AddField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='ssjaikskkakas', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
