# Generated by Django 5.0 on 2024-02-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='YTCQXl#b[[)a', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
