# Generated by Django 5.0 on 2024-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercustomised_is_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='a|MmXtdCc!<k', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
