# Generated by Django 5.0 on 2023-12-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercustomised_is_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Compte actif ? '),
        ),
    ]
