# Generated by Django 5.0 on 2024-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='#>bV{gI$:&w-', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
