# Generated by Django 5.0 on 2023-12-26 17:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usercustomised_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmationModel',
            fields=[
                ('email_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='id_email')),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2023, 12, 26, 18, 53, 29, 569436, tzinfo=datetime.timezone.utc), verbose_name='Expiration Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
