# Generated by Django 5.0 on 2023-12-26 22:54

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailconfirmationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='email_id',
            field=models.UUIDField(default=uuid.UUID('293a3d13-a206-449b-ad0d-a10de9d9418c'), primary_key=True, serialize=False, verbose_name='id_email'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 23, 54, 51, 526314, tzinfo=datetime.timezone.utc), verbose_name='Expiration Date'),
        ),
    ]
