# Generated by Django 5.0.2 on 2024-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='DX(:qH}tc3.u', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
