# Generated by Django 5.0 on 2023-12-26 23:51

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_emailconfirmationmodel_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='email_id',
            field=models.UUIDField(default=uuid.UUID('56b88d53-27d8-4c5e-8a59-757ab50d1369'), primary_key=True, serialize=False, verbose_name='id_email'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 0, 51, 16, 976438, tzinfo=datetime.timezone.utc), verbose_name='Expiration Date'),
        ),
    ]
