# Generated by Django 5.0 on 2023-12-27 01:03

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_emailconfirmationmodel_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='email_id',
            field=models.UUIDField(default=uuid.UUID('fb92fe05-60b1-4767-9781-ccc76a92afd5'), primary_key=True, serialize=False, verbose_name='id_email'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 2, 3, 44, 537612, tzinfo=datetime.timezone.utc), verbose_name='Expiration Date'),
        ),
    ]
