# Generated by Django 5.0 on 2023-12-27 17:08

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_emailconfirmationmodel_email_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustomised',
            options={'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='email_id',
            field=models.UUIDField(default=uuid.UUID('c5bc123c-4c5c-4346-9a3f-c1c290e04d23'), primary_key=True, serialize=False, verbose_name='id_email'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 18, 8, 56, 210232, tzinfo=datetime.timezone.utc), verbose_name='Expiration Date'),
        ),
    ]
