# Generated by Django 5.0.2 on 2024-02-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='5!Q{7_M:d-G!', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
