# Generated by Django 5.0.2 on 2024-02-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='WS&ABi+jH4p7', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
