# Generated by Django 5.0.2 on 2024-03-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='!MzGH+j0xO_l', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
