# Generated by Django 5.0.2 on 2024-03-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='):?U2Nx?1t|x', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
