# Generated by Django 5.0 on 2023-12-28 23:31

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_emailconfirmationmodel_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='email_id',
            field=models.UUIDField(default=uuid.UUID('89b097e5-5788-4260-88ca-cbc136d5669c'), primary_key=True, serialize=False, verbose_name='id_email'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 0, 31, 0, 662703, tzinfo=datetime.timezone.utc), verbose_name='Expiration Date'),
        ),
    ]
