# Generated by Django 5.0 on 2023-12-28 23:32

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_emailconfirmationmodel_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='email_id',
            field=models.UUIDField(default=uuid.UUID('a3e7dc23-3601-4ccb-8f26-644d7df85f3a'), primary_key=True, serialize=False, verbose_name='id_email'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 0, 32, 23, 273985, tzinfo=datetime.timezone.utc), verbose_name='Expiration Date'),
        ),
    ]
