# Generated by Django 5.0.2 on 2024-03-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='@2l}AtOp%BAx', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
