# Generated by Django 5.0.2 on 2024-03-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomised',
            name='algorithm',
            field=models.CharField(choices=[('alg1', 'Algorithm 1'), ('alg2', 'Algorithm 2'), ('alg3', 'Algorithm 3')], default='alg1', max_length=50, verbose_name='Algorithm'),
        ),
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='tzEB!S5yG81@', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
