# Generated by Django 5.0.2 on 2024-03-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_usercustomised_algorithm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='G&|qC1CPGs{A', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
