# Generated by Django 5.0.2 on 2024-03-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default=')}e_;GQ8Mqqc', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
