# Generated by Django 5.0.2 on 2024-03-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='o7cS%Nwy$w=4', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
