# Generated by Django 5.0.2 on 2024-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_usercustomised_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='&V6b[;s-hdZE', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
