# Generated by Django 5.0.2 on 2024-03-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_usercustomised_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='3Dcg45d<%U(E', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
