# Generated by Django 5.0.2 on 2024-03-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_usercustomised_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='RUQc?80Rb3Qu', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
