# Generated by Django 5.0.2 on 2024-03-18 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Articles', '0002_category_article_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('articleList', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(to='Articles.article')),
            ],
        ),
    ]
